version: "3.9"

services:
  minio:
    image: "minio/minio"
    container_name: "minio"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "${PWD}/data/:/data"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio-minio"
    command:
      - "server"
      - "/data"
