version: "3.9"

services:
  xxl-job:
    image: "registry.cn-shanghai.aliyuncs.com/yingzhuo/xxl-job:2.3.0"
    container_name: "xxl-job"
    restart: "always"
    entrypoint: "docker-entrypoint.sh"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://192.168.10.115:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=root"
