version: "3.9"

services:
  elasticsearch:
    image: "elasticsearch:5.6.16-alpine"
    container_name: "elastic-es"
    restart: "always"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "${PWD}/es_data/:/usr/share/elasticsearch/data/"
    environment:
      - "cluster.name=docker-cluster"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    command: "elasticsearch -Etransport.host=0.0.0.0"

  kibana:
    image: "kibana:5.6.16"
    container_name: "elastic-kibana"
    restart: "always"
    links:
      - "elasticsearch:elasticsearch"
    ports:
      - "5601:5601"
    environment:
      - "SERVER_NAME=kibana"
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  nginx:
    image: "nginx:1.17.2"
    container_name: "elastic-nginx"
    restart: "always"
    ports:
      - "15601:5601"
      - "19200:9200"
    links:
      - "elasticsearch:elasticsearch"
      - "kibana:kibana"
    volumes:
      - "${PWD}/cnf-nginx/nginx.conf/:/etc/nginx/nginx.conf:ro"
      - "${PWD}/cnf-nginx/password.db:/password.db:ro"
