version: "3.9"

services:
  mysql:
    image: "mysql:5.7.33"
    container_name: mysql
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/datadir/:/var/lib/mysql/
      - ${PWD}/conf/:/etc/mysql/conf.d
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=root"
