version: "3.9"

services:
  redis:
    image: "redis:6.0.8:-alpine"
    container_name: redis
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/data/:/data
    environment:
      - "TZ=Asia/Shanghai"
    command: "redis-server --appendonly yes --requirepass root"
