userPassword: true
password: "root"

cluster:
  enabled: false
  slaveCount: 1

slave:
  persistence:
    enabled: false

persistence:
  existingClaim: "helm-pvc-redis"

securityContext:
  enabled: true
  fsGroup: 0
  runAsUser: 0
