version: "3.9"

services:
  mongo:
    image: "mongo:4.0.23"
    container_name: "mongodb"
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - ${PWD}/data/:/data/db/
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root"
      - "TZ=Asia/Shanghai"
